#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# Secrets land beside the app, in the file the dev server already reads and
# git already ignores. Resolved from this script's own location so the wizard
# works from any working directory.
ENV_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/app/.env.local"

REDIRECT_URI="http://localhost:3000/api/auth/callback/google"

banner "Google sign-in for LFCA Practice"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "A Google Cloud project to hold the client"
say "Everything else hangs off a project. If you already have one you're happy"
say "to reuse, pick it instead of making another."
open_url "https://console.cloud.google.com/projectcreate"
step "Name it something you'll recognise later — 'lfca-practice' is fine."
step "Leave the organisation as 'No organisation'."
step "Create it, then make sure it's the project selected in the top bar."
note "A personal Gmail account has no organisation. That's expected."
pause "Project selected?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Register the app on the Google Auth Platform"
say "Google now requires an app registration before a client can be created."
say "This is the screen people see when they choose an account."
open_url "https://console.cloud.google.com/auth/branding"
step "Fill in the app name and your support email, then save."
note "Google's docs say 'fill out the form' without listing which fields are"
note "strictly required, so fill what it asks for. A logo and app domain are"
note "only needed for brand verification, which this app does not need."
pause "Registered?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Audience: External, and add yourself as a test user"
warn "This is the stage people skip, and it is the one that breaks sign-in."
say "With no Workspace organisation, External is the only available audience."
say "An app in Testing serves ONLY the accounts listed as test users — so if"
say "you are not on that list, your own sign-in will be refused."
open_url "https://console.cloud.google.com/auth/audience"
step "Confirm the user type is External."
step "Under 'Test users', click Add users and add the Google address you will"
step "  sign in with. Save."
note "The cap is 100 test users. You need one."
warn "In Testing status, an authorisation expires SEVEN DAYS after you consent."
warn "When sign-in suddenly asks for consent again next week, that is this —"
warn "not a bug, and not something to debug."
pause "Are you on the test-user list?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Create the OAuth client"
say "One client, for a web application, pointed at your local dev server."
open_url "https://console.cloud.google.com/auth/clients"
step "Click 'Create client'."
step "Application type: Web application."
step "Name: anything — 'lfca-practice local' works."
say ""
say "Authorised JavaScript origins — add both:"
step "  http://localhost:3000"
step "  http://localhost"
say ""
say "Authorised redirect URI — add exactly this, path included:"
step "  ${REDIRECT_URI}"
note "That path is Better Auth's, not Google's. It must match character for"
note "character or the callback fails with redirect_uri_mismatch."
note "Plain http is allowed here: localhost is exempt from Google's HTTPS rule."
say ""
step "Click Create. Do not close the dialog that appears."
pause "Client created, dialog open?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Capture the client id and secret"
warn "The secret is shown ONCE, in the dialog you have open now. Afterwards the"
warn "console shows only its last four characters. If you lose it you create a"
warn "new secret, you do not recover this one."
step "Copy the Client ID from the dialog."
ask GOOGLE_CLIENT_ID "Paste the client ID:"
step "Copy the Client secret from the same dialog."
ask_secret GOOGLE_CLIENT_SECRET "Paste the client secret (hidden):"
write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
write_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
note "There is also a JSON download in that dialog. Keep it or don't — these"
note "two values are all the app needs, and they are now saved."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "The session signing secret"
say "This one is generated here, not fetched from anywhere. It signs session"
say "tokens; changing it later logs every browser out, which is the intended"
say "emergency control rather than a hazard."
GENERATED_SECRET="$(openssl rand -base64 32)"
write_env BETTER_AUTH_SECRET "$GENERATED_SECRET"
write_env BETTER_AUTH_URL "http://localhost:3000"
note "Generated with openssl and written straight to the env file — it was"
note "never displayed, so it cannot end up in your scrollback."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "The allowlist — the thing that keeps this private"
say "Google sign-in is open to every Google account on earth unless it is"
say "closed. This variable is what closes it."
say ""
say "An account not on this list gets no user row, no session, and no way in."
warn "An EMPTY value rejects everyone, including you. That is deliberate: a"
warn "variable that meant 'allow everyone' when blank would publish the app by"
warn "accident."
ask ALLOWED_EMAILS "Your Google address (comma-separated for more than one):"
if [[ -z "$ALLOWED_EMAILS" ]]; then
  warn "Left empty — every sign-in will be refused until you set it."
  SKIPPED+=("ALLOWED_EMAILS is empty; no one can sign in")
fi
write_env ALLOWED_EMAILS "$ALLOWED_EMAILS"

finish

printf '  %sNext:%s start the app and sign in.\n\n' "$BOLD" "$RESET"
printf '    cd app && npm run dev\n\n'
printf '  %sIf sign-in fails, in order of likelihood:%s\n' "$DIM" "$RESET"
printf '    redirect_uri_mismatch  → the redirect URI is not character-identical\n'
printf '    access_blocked         → you are not on the test-user list (stage 3)\n'
printf '    signed in but refused  → your address is not in ALLOWED_EMAILS\n'
printf '    consent asked again    → normal: Testing-status consent lapses after 7 days\n'
printf '\n'
printf '  %sERR_SSL_PROTOCOL_ERROR on localhost is the browser, not the app.%s\n' "$DIM" "$RESET"
printf '    The dev server speaks plain http. Type the scheme in full —\n'
printf '    http://localhost:3000 — and if it still upgrades, delete the cached\n'
printf '    HSTS pin at chrome://net-internals/#hsts (enter "localhost").\n'
printf '    Do NOT switch to 127.0.0.1: Google treats it as a different origin\n'
printf '    from localhost, and only localhost is registered on the client.\n\n'
