#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

REPO="yutaasakura96/lfca-lab"
ROOT_DIR="app"
MAIN_ENV="app/.env.main"     # the two production connection strings (#44)
LOCAL_ENV="app/.env.local"   # Google client + allowlist, shared with local (doc 12 §1)
VERCEL="npx --yes vercel@latest"

# ── helpers specific to this wizard ───────────────────────────────────────

# read_env FILE KEY — the value of KEY, unquoted. Never printed by the caller.
# `cut -d= -f2-` rather than -f2 because a connection string is full of '='.
read_env() {
  [[ -f "$1" ]] || return 1
  local line; line=$(grep -E "^${2}=" "$1" | tail -n1) || return 1
  line="${line#*=}"; line="${line%\"}"; line="${line#\"}"
  [[ -n "$line" ]] || return 1
  printf '%s' "$line"
}

# push_env NAME FILE — send one value to Vercel's production environment,
# piped from the file so it never reaches the screen, the shell history, or an
# agent's context. `--force` overwrites on a re-run, which makes this wizard
# idempotent. Documented stdin sibling is `vercel env update`, if `add` ever
# stops accepting it.
push_env() {
  local name="$1" file="$2" value
  if ! value=$(read_env "$file" "$name"); then
    SKIPPED+=("$name (not found in $file — set it by hand in the dashboard)")
    warn "$name is not in $file; skipping"
    return 0
  fi
  if printf '%s' "$value" | $VERCEL env add "$name" production --force --cwd "$ROOT_DIR" >/dev/null 2>&1; then
    printf '  %s✓ set%s %s in Vercel production %s(%d chars, not shown)%s\n' \
      "$GREEN" "$RESET" "$name" "$DIM" "${#value}" "$RESET"
  else
    SKIPPED+=("$name (vercel env add failed — add it in the dashboard)")
    warn "could not set $name — see the dashboard"
  fi
}

die() { printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET"; exit 1; }

banner "Vercel production — lfca-lab #46"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight — the configuration must be on main first"
say "Nothing here touches Vercel. These are the things that must already be"
say "true, because connecting the project before they are is what mints a"
say "public URL for every branch."
printf '\n'

command -v git >/dev/null 2>&1 || die "git is not on PATH."
command -v node >/dev/null 2>&1 || die "node is not on PATH."

git -C . diff --quiet && git -C . diff --cached --quiet \
  || die "The working tree is dirty. Commit or stash before connecting production."

git fetch -q origin 2>/dev/null || warn "could not reach origin; comparing against the last fetch"
[[ "$(git rev-parse main)" == "$(git rev-parse origin/main)" ]] \
  || die "main and origin/main differ. Push main before connecting Vercel."

git show "main:${ROOT_DIR}/vercel.json" >/dev/null 2>&1 \
  || die "${ROOT_DIR}/vercel.json is not on main. It is what stops every branch deploying — it must be on main BEFORE the project exists."

if git show "main:${ROOT_DIR}/vercel.json" | node -e '
  let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{
    const c=JSON.parse(s), d=c.git&&c.git.deploymentEnabled;
    const ok = d && typeof d==="object" && d["**"]===false && d.main===true
      && Object.values(d).filter(Boolean).length===1 && c.buildCommand==="next build";
    process.exit(ok?0:1);
  })'; then
  printf '  %s✓%s main carries the branch map and the pinned build command\n' "$GREEN" "$RESET"
else
  die "${ROOT_DIR}/vercel.json on main is not the expected shape. Run: cd app && npm run test:unit"
fi

[[ -f "$MAIN_ENV" ]] || die "$MAIN_ENV is missing — it holds the two production connection strings (#44)."
read_env "$MAIN_ENV" DATABASE_URL >/dev/null || die "DATABASE_URL is not in $MAIN_ENV."
read_env "$MAIN_ENV" DATABASE_URL_UNPOOLED >/dev/null || die "DATABASE_URL_UNPOOLED is not in $MAIN_ENV."
printf '  %s✓%s %s holds both connection strings\n' "$GREEN" "$RESET" "$MAIN_ENV"

[[ -f "$LOCAL_ENV" ]] || die "$LOCAL_ENV is missing — the Google client and allowlist come from it."
printf '  %s✓%s %s is present\n' "$GREEN" "$RESET" "$LOCAL_ENV"
printf '\n'
pause "Press Enter to create the Vercel project"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Create the project — Root Directory is the one setting that matters"
say "Root Directory cannot be set from the CLI or from vercel.json. It is a"
say "dashboard setting, so this is the one stage that is entirely yours."
printf '\n'
open_url "https://vercel.com/new"
step "Import  $REPO  (Add New… → Project → Import)."
step "Before deploying, click Edit beside Root Directory and set it to:  $ROOT_DIR"
step "Leave 'Include source files outside of the Root Directory' ON (the default)."
step "Leave Build Command alone — ${ROOT_DIR}/vercel.json pins it to 'next build'."
step "Do NOT paste any environment variables here. The next stages send them"
say  "  straight from your files, so no secret passes through a browser field."
step "Click Deploy."
printf '\n'
warn "This first build may FAIL, and that is expected — it has no database URL yet."
note "Stages 4 and 5 set the variables; stage 6 redeploys."
printf '\n'
pause "Press Enter once the project exists (failed build and all)"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Link this checkout to the project"
say "So the CLI knows which project the next two stages are writing to."
say "Both commands are interactive and will talk to you directly."
printf '\n'
step "Signing in to Vercel (opens a browser):"
printf '\n'
( cd "$ROOT_DIR" && $VERCEL login ) || warn "login reported a problem — if you were already signed in, carry on"
printf '\n'
step "Linking ${ROOT_DIR}/ to the project you just created:"
printf '\n'
( cd "$ROOT_DIR" && $VERCEL link ) || die "vercel link failed — cannot set variables without it."
printf '\n'
printf '  %s✓%s linked\n' "$GREEN" "$RESET"
pause "Press Enter to send the connection strings"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "The two connection strings"
say "Read from $MAIN_ENV and piped into Vercel. Neither value is printed here,"
say "and neither reaches your shell history."
printf '\n'
note "Both already carry sslmode=verify-full and channel_binding=require (doc 12 §2.1)."
printf '\n'
push_env DATABASE_URL "$MAIN_ENV"
push_env DATABASE_URL_UNPOOLED "$MAIN_ENV"
printf '\n'
note "DATABASE_URL is the pooled host, read by the app."
note "DATABASE_URL_UNPOOLED is the direct host, read by #48's migrate and seed."
printf '\n'
pause "Press Enter to send the Google client and the allowlist"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "The Google client and the allowlist"
say "One OAuth client serves both environments (doc 12 §1), so these three are"
say "the same values local uses — read from $LOCAL_ENV."
printf '\n'
push_env GOOGLE_CLIENT_ID "$LOCAL_ENV"
push_env GOOGLE_CLIENT_SECRET "$LOCAL_ENV"
push_env ALLOWED_EMAILS "$LOCAL_ENV"
printf '\n'
warn "ALLOWED_EMAILS is the only thing between this app and a public one."
note "An empty or unset value refuses EVERY sign-in, which is the safe default (doc 08 §3)."
printf '\n'
note "Deliberately NOT set here — both are #47's, and both need a hostname that"
note "does not exist until the first successful deploy:"
note "  BETTER_AUTH_URL     the canonical origin"
note "  BETTER_AUTH_SECRET  production-only, different from the local value"
printf '\n'
pause "Press Enter to redeploy and check the sign-in redirect"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Redeploy, and observe the sign-in redirect"
say "Every route is behind the session gate, so a working deployment looks like"
say "a redirect to /sign-in. That is #46's bar — signing in is #47."
printf '\n'
step "Redeploying production with the variables now in place:"
printf '\n'
( cd "$ROOT_DIR" && $VERCEL --prod ) || warn "the CLI deploy reported a problem — check the dashboard"
printf '\n'
ask PRODUCTION_URL "Paste the production URL (https://…):"
[[ -n "${PRODUCTION_URL:-}" ]] || die "No URL given; cannot check the redirect."
PRODUCTION_URL="${PRODUCTION_URL%/}"
printf '\n'
step "Asking $PRODUCTION_URL/ what it does with an unauthenticated visitor:"
CODE=$(curl -s -o /dev/null -w '%{http_code}' "$PRODUCTION_URL/" || echo "000")
LOC=$(curl -s -o /dev/null -w '%{redirect_url}' "$PRODUCTION_URL/" || echo "")
printf '  status %s   location %s\n' "$CODE" "${LOC:-—}"
if [[ "$LOC" == *"/sign-in"* ]]; then
  printf '  %s✓ redirects to the sign-in screen — #46 criterion met%s\n' "$GREEN" "$RESET"
elif [[ "$CODE" == "200" ]]; then
  warn "200 with no redirect. If this is the sign-in page itself, fine; if it is the home screen, the session gate is not doing its job."
else
  warn "unexpected — check the deployment logs in the dashboard."
fi
printf '\n'
pause "Press Enter for the last stage: proving develop deploys nothing"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Prove develop mints nothing — and why this is the load-bearing check"
say "This is not only #46's criterion. It is the ONLY proof that Vercel read"
say "${ROOT_DIR}/vercel.json at all: the file's placement rests on Vercel's own"
say "monorepo docs showing apps/web/vercel.json, not on a documented rule"
say "(doc 12 §3.1). If it were in the wrong place, develop would deploy."
printf '\n'
if confirm "Push an empty commit to develop now to test it?"; then
  git switch develop -q
  git commit -q --allow-empty -m "chore: confirm develop mints no deployment"
  git push -q origin develop
  printf '  %s✓%s pushed an empty commit to develop\n' "$GREEN" "$RESET"
  printf '\n'
  open_url "https://vercel.com/dashboard"
  step "Watch the project's Deployments tab for about a minute."
  step "EXPECTED: no new deployment appears."
  step "If one DOES appear, ${ROOT_DIR}/vercel.json was not read — move it to the"
  say  "  repository root, push, and run this stage again."
  printf '\n'
  pause "Press Enter once you have watched"
  if confirm "Did develop correctly produce NO deployment?"; then
    printf '  %s✓ non-production deployments are off, and the file was read%s\n' "$GREEN" "$RESET"
  else
    SKIPPED+=("develop DID deploy — vercel.json was not read; see doc 12 §3.1")
    warn "recorded as unmet"
  fi
else
  SKIPPED+=("the develop-mints-nothing observation (#46's load-bearing check)")
fi
printf '\n'
say "The third carried question — whether Vercel skips builds for content-only"
say "commits — needs no observation. It requires a package workspace:"
if node -e 'const p=require("./package.json");process.exit(p.workspaces?1:0)' \
   && [[ ! -f pnpm-workspace.yaml ]]; then
  printf '  %s✓%s no workspaces key, no pnpm-workspace.yaml — the behaviour cannot apply here\n' "$GREEN" "$RESET"
  note "Vercel documents non-workspace changes as global changes that deploy everything."
else
  warn "a workspace now exists — re-read the carried finding, it may apply after all"
fi

finish

printf '  %sNext:%s #47 — add the production redirect URI to the Google client,\n' "$BOLD" "$RESET"
printf '  then set BETTER_AUTH_URL and a production-only BETTER_AUTH_SECRET.\n'
[[ -n "${PRODUCTION_URL:-}" ]] && printf '  The origin #47 needs is: %s%s%s\n' "$BOLD" "$PRODUCTION_URL" "$RESET"
printf '\n'
