#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=7

ROOT_DIR="app"
VERCEL="npx --yes vercel@latest"

# ── helpers specific to this wizard ───────────────────────────────────────

die() { printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET"; exit 1; }

# in_production NAME — whether Vercel production already holds NAME. Names only;
# `vercel env ls` never prints values.
in_production() {
  $VERCEL env ls production --cwd "$ROOT_DIR" 2>/dev/null | grep -qE "^\s*${1}\s"
}

# push_value NAME VALUE [EXTRA…] — pipe one value into Vercel production. Never
# echoed; `--force` overwrites, so a re-run replaces rather than duplicates.
# EXTRA is passed through to `vercel env add` — `--type config` for the DSN.
#
# **The exit code is not the check, and that is not caution but experience.**
# Measured 2026-09-18: `vercel env add NEXT_PUBLIC_SENTRY_DSN production` prints
# `{"status": "action_required", "reason": "public_prefix_requires_type"}`,
# saves nothing, and **exits 0**. The first run of this wizard reported the DSN
# set twice over while production never held it. So every value is read back
# from the listing — which prints names, never values — and a name that is not
# there is a failure however cheerfully the CLI exited.
push_value() {
  local name="$1" value="$2"; shift 2
  if [[ -z "$value" ]]; then
    SKIPPED+=("$name (no value given)")
    warn "$name was empty; skipping"
    return 0
  fi

  local output status=0
  output=$(printf '%s' "$value" | $VERCEL env add "$name" production --force "$@" --cwd "$ROOT_DIR" 2>&1) || status=$?

  if [[ $status -eq 0 ]] && in_production "$name"; then
    printf '  %s✓ set%s %s in Vercel production %s(%d chars, not shown)%s\n' \
      "$GREEN" "$RESET" "$name" "$DIM" "${#value}" "$RESET"
    return 0
  fi

  SKIPPED+=("$name (not saved — see the message above)")
  warn "$name did NOT save. What the CLI said:"
  # The value is never in this output — the CLI echoes the name and its own
  # refusal, not what was piped in.
  printf '%s\n' "$output" | grep -vE '^(Vercel CLI|Retrieving|Saving|Next steps:|- |  vercel)' \
    | sed '/^[[:space:]]*$/d' | head -12 | sed 's/^/    /'
}

banner "Sentry for production — lfca-lab #52"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight — the Vercel CLI can reach the project"
say "Four values end up in Vercel production and nowhere else. Nothing is"
say "written locally: Sentry stays off on this laptop because no DSN is set"
say "there (doc 12 §1)."
printf '\n'
command -v node >/dev/null 2>&1 || die "node is not on PATH."
if $VERCEL env ls production --cwd "$ROOT_DIR" >/dev/null 2>&1; then
  printf '  %s✓%s the Vercel CLI lists production variables for %s/\n' "$GREEN" "$RESET" "$ROOT_DIR"
else
  die "vercel env ls failed. Run: npx --yes vercel@latest login   then re-run this wizard."
fi
for name in NEXT_PUBLIC_SENTRY_DSN SENTRY_AUTH_TOKEN SENTRY_ORG SENTRY_PROJECT; do
  if in_production "$name"; then
    note "$name is already set — this run will overwrite it"
  fi
done
printf '\n'
pause "Press Enter to create the Sentry account"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Create the account and the organization"
open_url "https://sentry.io/signup/"
step "Sign up with the owner's account — the free Developer plan is enough (doc 03 §10)."
step "When asked where to store data, pick either region. It cannot be changed"
say  "  later, and nothing in this app depends on which."
step "Create the organization. Its slug is in the address bar afterwards:"
say  "  https://<org-slug>.sentry.io/…"
printf '\n'
note "If Sentry starts a setup flow that tells you to run  npx @sentry/wizard,"
note "do NOT run it — it rewrites next.config.ts and adds replay and tracing,"
note "which #52 declined. The agent wires the SDK by hand."
printf '\n'
ask SENTRY_ORG "Organization slug:"
[[ -n "${SENTRY_ORG:-}" ]] || die "No organization slug given."
pause "Press Enter to create the project"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Create the project"
open_url "https://sentry.io/organizations/${SENTRY_ORG}/projects/new/"
step "Platform: Next.js."
step "Alert frequency: keep the default that alerts on new or high-priority issues."
say  "  That rule emails you, which is doc 12 §6's whole monitoring plan."
step "Project name: something like  lfca-lab . Create it."
step "Skip the install instructions it shows next (see the last stage's note)."
printf '\n'
note "The slug is the last path segment of the project's settings URL:"
note "  …/settings/projects/<project-slug>/"
printf '\n'
ask SENTRY_PROJECT "Project slug:"
[[ -n "${SENTRY_PROJECT:-}" ]] || die "No project slug given."
pause "Press Enter to check the server-side scrubbing"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Keep Sentry's own scrubbing on — the second layer"
say "The app scrubs every event before it leaves (src/domain/scrub.ts). Sentry's"
say "server-side scrubbing stays on behind it, so a miss in one is caught by the other."
printf '\n'
open_url "https://sentry.io/settings/${SENTRY_ORG}/projects/${SENTRY_PROJECT}/security-and-privacy/"
step "Data Scrubber: ON."
step "Use Default Scrubbers: ON."
step "Prevent Storing of IP Addresses: ON."
printf '\n'
note "If the page is not found, it is Project Settings → Security & Privacy."
note "An organization-level setting that is already on greys the project toggle out — that is fine."
printf '\n'
pause "Press Enter once all three are on"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "The DSN"
say "Public by design (doc 12 §2) — it is inlined into the browser bundle, which is"
say "why the name carries NEXT_PUBLIC_. The server reads the same variable."
printf '\n'
open_url "https://sentry.io/settings/${SENTRY_ORG}/projects/${SENTRY_PROJECT}/keys/"
step "Client Keys (DSN) → copy the DSN:  https://…@….ingest….sentry.io/<digits>"
printf '\n'
ask_secret SENTRY_DSN_VALUE "Paste the DSN (hidden, to keep it out of scrollback):"
if [[ ! "${SENTRY_DSN_VALUE:-}" =~ ^https://[^@]+@[^/]+/[0-9]+$ ]]; then
  warn "that does not look like a DSN (https://key@host/digits)"
  confirm "Send it anyway?" || die "Stopped before sending a malformed DSN."
fi
# `--type config` is required rather than stylistic. The CLI refuses to store a
# NEXT_PUBLIC_ name without being told which it is — `config` (readable, and
# therefore inlinable into the browser bundle) or `secret` (hidden, and useless
# to a browser). A DSN is the first: it names a project to write to and carries
# no authority to read anything back, which is why every browser app on Sentry
# ships one.
push_value NEXT_PUBLIC_SENTRY_DSN "${SENTRY_DSN_VALUE:-}" --type config
unset SENTRY_DSN_VALUE
printf '\n'
pause "Press Enter for the build-time auth token"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "The build-time auth token — the one real secret here"
say "Used only by next build, to upload source maps. It never reaches the browser"
say "and the app never reads it at runtime."
printf '\n'
open_url "https://sentry.io/settings/${SENTRY_ORG}/auth-tokens/"
step "Organization Tokens → Create New Token."
step "Name it  vercel-production-build . Copy it — Sentry shows it once."
note "If that page is not found: Settings → Developer Settings → Organization Tokens."
printf '\n'
ask_secret SENTRY_AUTH_TOKEN_VALUE "Paste the token (hidden):"
if [[ ! "${SENTRY_AUTH_TOKEN_VALUE:-}" =~ ^sntrys_ ]]; then
  warn "organization tokens normally begin with sntrys_ — this one does not"
  confirm "Send it anyway?" || die "Stopped before sending the token."
fi
push_value SENTRY_AUTH_TOKEN "${SENTRY_AUTH_TOKEN_VALUE:-}"
unset SENTRY_AUTH_TOKEN_VALUE
printf '\n'
pause "Press Enter to send the two slugs and check the result"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "The slugs, and what production now holds"
say "Plain configuration, read by withSentryConfig at build time rather than"
say "committed."
printf '\n'
push_value SENTRY_ORG "$SENTRY_ORG"
push_value SENTRY_PROJECT "$SENTRY_PROJECT"
printf '\n'
step "Names now in Vercel production (values are never listed):"
for name in NEXT_PUBLIC_SENTRY_DSN SENTRY_AUTH_TOKEN SENTRY_ORG SENTRY_PROJECT; do
  if in_production "$name"; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$name"
  else
    warn "$name is missing"
    SKIPPED+=("$name is not in Vercel production")
  fi
done
printf '\n'
note "Nothing is redeployed. A variable reaches only a new build, and the SDK is"
note "not on main yet — the next push to main after it lands picks these up."
printf '\n'
pause "Press Enter to finish"

finish

printf '  %sNext:%s tell the agent the wizard is done. It lands the SDK on main,\n' "$BOLD" "$RESET"
printf '  then triggers the deliberate production error and watches it arrive.\n\n'
